import Head from "next/head";
import Image from "next/image";
import { useState } from "react";
import styled from "styled-components";
import { RaffleForm } from "../../Components/RaffleForm/RaffleForm";
import Menu from "../../Components/sideMenu/Menu";
import SideNavBar from "../../Components/sideMenu/SideNavBar";
import { Header } from "../../Components/Header/Header";

interface ReleasePageProps{
  postData: {title: string; colorway: string;}[]
}

export default function ReleasePage({ postData }: ReleasePageProps) {
  const [open, setOpen] = useState(false);

  return (
    <Container>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Container>
        <HeaderContainer>
          <Header type={""} />
          <SearchNavContainer>
            <NavContainer>
              <SideNavBar open={open} setOpen={setOpen} />
              <Menu open={open} setOpen={setOpen} />
            </NavContainer>
          </SearchNavContainer>
        </HeaderContainer>
        <RaffleForm postData={postData[0]} />
      </Container>
      <footer></footer>
    </Container>
  );
}

export async function getAllPostIds() {
  const res = await fetch("https://sneaker-mern-app.herokuapp.com/posts/");
  const posts = await res.json();
  return posts?.map((post : {_id: string, title: string}) => {
    const postID = post._id;
    const stringPostId = postID.toString();
    return {
      params: {
        nameColorway: post.title + "_" + stringPostId,
      },
    };
  });
}

export async function getStaticPaths() {
  const paths = await getAllPostIds();
  return {
    paths,
    fallback: false,
  };
}

export async function getPostData(id : string) {
  const res = await fetch(`https://sneaker-mern-app.herokuapp.com/posts/${id}`);
  const post = await res.json();

  // Combine the data with the id
  return {
    id,
    ...post,
  };
}

export interface getStaticPropsTypes{
  params: {
    nameColorway: string
  }
}

export async function getStaticProps({ params }: getStaticPropsTypes) {
  let id = params.nameColorway.split("_")[1];
  const postData = await getPostData(id);
  return {
    props: {
      postData,
    },
  };
}

const Container = styled.div`
  width: 100%;
  height: 100vh;
  display: flex;
  flex-direction: column;
  align-items: center;
  background-color: #f5f5f5;
`;


const HeaderContainer = styled.div`
  display: flex;
  flex-direction: row;
  justify-content: space-between;
  align-items: center;
  width: 100%;
`;

const SearchNavContainer = styled.div`
  display: flex;
`;

const NavContainer = styled.div`
  display: flex;
  justify-content: center;
  align-items: center;
`;
