import Head from "next/head";
import Image from "next/image";
import { useState } from "react";
import styled from "styled-components";
import { useDispatch, useSelector } from "react-redux";
import { ReleaseInfoPage } from "../../Components/ReleaseInfo/ReleaseInfoPage";
import { fetchSneakerInfo, setCurrentShoe } from "../../store/releaseInfo";
import { useRouter } from "next/router";
import { RaffleForm } from "../../Components/RaffleForm/RaffleForm";
import Menu from "../../Components/sideMenu/Menu";
import SideNavBar from "../../Components/sideMenu/SideNavBar";
import { Header } from "../../Components/Header/Header";

export default function ReleasePage({ postData }) {
  const [open, setOpen] = useState(false);

  return (
    <Container>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Container>
        <div>
          <Menu open={open} setOpen={setOpen} />
          <SideNavBar open={open} setOpen={setOpen} />
        </div>
         <Header />
         
        <RaffleForm postData={postData[0]} />
      </Container>
      <footer></footer>
    </Container>
  );
}

export async function getAllPostIds() {
  const res = await fetch("https://sneaker-mern-app.herokuapp.com/posts/");
  const posts = await res.json();
  return posts.map((post) => {
    const postID = post._id;
    const stringPostId = postID.toString();
    return {
      params: {
        nameColorway: post.title + "_" + stringPostId,
      },
    };
  });
}

export async function getStaticPaths() {
  const paths = await getAllPostIds();
  return {
    paths,
    fallback: false,
  };
}

export async function getPostData(id) {
  const res = await fetch(`https://sneaker-mern-app.herokuapp.com/posts/${id}`);
  const post = await res.json();

  // Combine the data with the id
  return {
    id,
    ...post,
  };
}

export async function getStaticProps({ params }) {
  let id = params.nameColorway.split("_")[1];
  const postData = await getPostData(id);
  return {
    props: {
      postData,
    },
  };
}

const Container = styled.div`
  width: 100%;
  height: 100vh;
  display: flex;
  flex-direction: column;
  align-items: center;
  background-color: #f5f5f5;
`;
