import Head from "next/head";
import Image from "next/image";
import { useState } from "react";
import styled from "styled-components";
// import { NavBar } from "../Components/NavBar/NavBar";
import { useDispatch, useSelector } from "react-redux";
import { ReleaseInfoPage } from "../../Components/ReleaseInfo/ReleaseInfoPage";
import { fetchSneakerInfo,setCurrentShoe } from "../../store/releaseInfo";
import { useRouter } from 'next/router'


export default function ReleasePage() {

  const router = useRouter()
  console.log(router.query);

  return (
    <Container>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* <Container>
        <ReleaseInfoPage data={locationData} />
        <NavBar />
      </Container> */}
      <footer></footer>
    </Container>
  );
}


// export async function getAllPostIds() {
//   // Instead of the file system,
//   // fetch post data from an external API endpoint
//   const res = await fetch("https://sneaker-mern-app.herokuapp.com/posts/");
//   const posts = await res.json();
//   return posts.map((post) => {
//     return {
//       params: {
//         nameColorway: post.title,
//       },
//     };
//   });
// }

// export async function getStaticPaths() {
//     const paths = getAllPostIds()
//     console.log(paths)
//     return {
//       paths,
//       fallback: false
//     }
//   }

const Container = styled.div`
  width: 100%;
  height: 100%;
  display: flex;
  flex-direction: column;
  justify-content: center;
  align-items: center;
  background-color: #f5f5f5;
`;
