import Head from "next/head";
import Image from "next/image";
import styled from "styled-components";
import { NavBar } from "../Components/NavBar/NavBar";
import { AboutMePage } from "../Components/AboutMePage/AboutMe";

export default function About() {
  return (
    <Container>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Container>
        <AboutMePage />
        <NavBar />
      </Container>
      <footer></footer>
    </Container>
  );
}

const Container = styled.div`
  width: 100%;
  height: 100%;
  display: flex;
  flex-direction: column;
  justify-content: center;
  align-items: center;
  background-color: #f5f5f5;
`;
