// auth.tsx
import React, { useState } from "react";
import Head from "next/head";
import StyledFirebaseAuth from "react-firebaseui/StyledFirebaseAuth";
import { Header } from "../Components/Header/Header";
import firebase from "../firebase/clientApp";
import styled from "styled-components";
import SideNavBar from "../Components/sideMenu/SideNavBar";
import Menu from "../Components/sideMenu/Menu";
import { DesktopMenu } from "../Components/desktopMenu/DesktopMenu";
import { SearchBar } from "../Components/SearchBar/SearchBar";

// Configure FirebaseUI.
const uiConfig = {
  // Redirect to / after sign in is successful. Alternatively you can provide a callbacks.signInSuccess function.
  signInSuccessUrl: "/",
  // GitHub as the only included Auth Provider.
  // You could add and configure more here!

  signInOptions: [
    firebase.auth.FacebookAuthProvider.PROVIDER_ID,
    firebase.auth.GoogleAuthProvider.PROVIDER_ID,
    { provider: firebase.auth.EmailAuthProvider.PROVIDER_ID },
  ],
};

const SignInScreen = () => {
  const [open, setOpen] = useState(false);
  return (
    <Container>
      <Head>
        <title>Blueprint Drops</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" />
        <link
          href="https://fonts.googleapis.com/css2?family=Inter&display=swap"
          rel="stylesheet"
        />
        <link
          href="https://fonts.googleapis.com/css2?family=Poppins:wght@500&display=swap"
          rel="stylesheet"
        ></link>
      </Head>
      <HeaderContainer>
        <Header type={""} />
        <DesktopMenu />
        <SearchNavContainer>
          <div>
            <SideNavBar open={open} setOpen={setOpen} />
            <Menu open={open} setOpen={setOpen} />
          </div>
        </SearchNavContainer>
      </HeaderContainer>
      <DesktopContentContainer>
        <SocialMediaLogin>
          <LoginHeader>Log in to Blueprint Drops</LoginHeader>
          <StyledFirebaseAuth
            uiConfig={uiConfig}
            firebaseAuth={firebase.auth()}
          />
        </SocialMediaLogin>
      </DesktopContentContainer>
    </Container>
  );
};

export default SignInScreen;

const HeaderContainer = styled.div`
  display: flex;
  flex-direction: row;
  justify-content: space-between;
  align-items: center;
  width: 100%;
  z-index: 30;

  @media (min-width: 768px) {
    border-top: 1px solid #c0c0c0;
    border-bottom: 1px solid #c0c0c0;
    padding: 20px;
    background-color: white;
    position: fixed;
    right: 0;
    left: 0;
    margin: 0 auto;
  }

  @media (min-width: 768px) and (max-width: 1024px) {
    font-size: 24px;
    width: 80%;
    padding: 10px 20px;
  }

  @media (min-width: 1024px) and (max-width: 1440px) {
    font-size: 29px;
    width: 80%;
    padding: 10px 20px;
  }

  @media (min-width: 1441px) {
    font-size: 29px;
    width: 70%;
    padding: 10px 20px;
  }

  @media (min-width: 1900px) and (max-width: 2500px) {
    width: 60%;
  }

  @media (min-width: 2500px) {
    width: 55%;
  }
`;

const SearchNavContainer = styled.div`
  display: flex;
`;

const SocialMediaLogin = styled.div`
  margin-top: 200px;
  width: 420px;
  background-color: #f5f5f5;
  padding-bottom: 100px;
  border-radius: 5px;

  @media (min-width: 768px) {
    filter: drop-shadow(0 0 0.3rem #e7eaed);
  }
`;

const DesktopContentContainer = styled.div`
  display: flex;
  flex-direction: column;
  align-items: center;
  height: 100vh;
  @media (min-width: 768px) {
    background-color: white;
  }

  @media (min-width: 768px) and (max-width: 1024px) {
    width: 80%;
  }

  @media (min-width: 1024px) and (max-width: 1440px) {
    width: 80%;
  }

  @media (min-width: 1441px) and (max-width: 1900px) {
    width: 70%;
  }

  @media (min-width: 1900px) and (max-width: 2500px) {
    width: 60%;
  }

  @media (min-width: 2500px) {
    width: 55%;
  }
`;
export const Container = styled.div`
  width: 100%;
  height: 100%;
  display: flex;
  flex-direction: column;
  justify-content: center;
  align-items: center;
  background-color: #f5f5f5;
  overflow: hidden;
`;

const LoginHeader = styled.p`
  font-size: 24px;
  text-align: center;
  letter-spacing: 0.5px;
  padding: 15px;
  font-weight: 600;
`;
