import Head from "next/head";
import styled from "styled-components";
import { Header } from "../Components/Header/Header";
import { PastPresent } from "../Components/Past-Present/PastPresent";
import { SneakerFeed } from "../Components/SneakerFeed/SneakerFeed";
import { Options } from "../Components/mensWomensKidsSelector/mensWomensKidsSelector";
import { SearchBar } from "../Components/SearchBar/SearchBar";
import { useDispatch, useSelector } from "react-redux";
import { useEffect } from "react";
import { fetchSneakerInfo } from "../store/releaseInfo";
import SideNavBar from "../Components/sideMenu/SideNavBar";
import Menu from "../Components/sideMenu/Menu";
import { useState } from "react";

export default function Home({ data }) {
  const dispatch = useDispatch();
  const info = useSelector((state) => {
    state.allSneakerInfo;
  });
  const [open, setOpen] = useState(false);

  useEffect(() => {
    dispatch(fetchSneakerInfo())
      .then(() => dispatch({ type: "sneaker/splitSneakerInfo" }))
      .then(() => dispatch({ type: "sneaker/filterMonths" }))
      .then(() => dispatch({ type: "sneaker/copyMonthsArray" }));
  }, []);

  return (
    <Container>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <div>
        <SideNavBar open={open} setOpen={setOpen} />
        <Menu open={open} setOpen={setOpen} />
      </div>
      <SearchBar />
      <PastPresent />
      <Options />
      <SneakerFeed />
      <footer></footer>
    </Container>
  );
}

const HeaderContainer = styled.div`
  display: flex;
  flex-direction: row;
`;

const Container = styled.div`
  width: 100%;
  height: 100%;
  display: flex;
  flex-direction: column;
  justify-content: center;
  align-items: center;
  background-color: #f5f5f5;
  overflow: hidden;
`;
